"""empty message

Revision ID: 2ce1ec00252b
Revises: 27e0efef50e1
Create Date: 2025-11-24 20:39:10.711588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ce1ec00252b'
down_revision: Union[str, Sequence[str], None] = '27e0efef50e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sleep_retrain_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('sleep_start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acc_x', sa.Float(), nullable=False),
    sa.Column('acc_y', sa.Float(), nullable=False),
    sa.Column('acc_z', sa.Float(), nullable=False),
    sa.Column('hr', sa.Float(), nullable=False),
    sa.Column('sleep_stage', sa.Integer(), nullable=False),
    sa.Column('sao2', sa.Float(), server_default='0', nullable=False),
    sa.Column('bvp', sa.Float(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sleep_retrain_log_measured_at'), 'sleep_retrain_log', ['measured_at'], unique=False)
    op.create_index(op.f('ix_sleep_retrain_log_user'), 'sleep_retrain_log', ['user'], unique=False)
    op.create_table('stress_retrain_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('heart_rate_bpm', sa.Float(), nullable=False),
    sa.Column('hrv_sdnn_ms', sa.Float(), nullable=False),
    sa.Column('hrv_rmssd_ms', sa.Float(), nullable=False),
    sa.Column('acc_x_mean', sa.Float(), nullable=False),
    sa.Column('acc_y_mean', sa.Float(), nullable=False),
    sa.Column('acc_z_mean', sa.Float(), nullable=False),
    sa.Column('acc_mag_mean', sa.Float(), nullable=False),
    sa.Column('acc_mag_std', sa.Float(), nullable=False),
    sa.Column('wrist_temperature_c_mean', sa.Float(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stress_retrain_log_user'), 'stress_retrain_log', ['user'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stress_retrain_log_user'), table_name='stress_retrain_log')
    op.drop_table('stress_retrain_log')
    op.drop_index(op.f('ix_sleep_retrain_log_user'), table_name='sleep_retrain_log')
    op.drop_index(op.f('ix_sleep_retrain_log_measured_at'), table_name='sleep_retrain_log')
    op.drop_table('sleep_retrain_log')
    # ### end Alembic commands ###
