"""empty message

Revision ID: 7f288bedb519
Revises: 
Create Date: 2025-11-12 16:29:48.064201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f288bedb519'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('robot',
    sa.Column('robot_id', sa.String(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['user.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('robot_id')
    )
    op.create_index(op.f('ix_robot_robot_id'), 'robot', ['robot_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_robot_robot_id'), table_name='robot')
    op.drop_table('robot')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
