"""empty message

Revision ID: c6a5710ac133
Revises: 2ce1ec00252b
Create Date: 2025-11-27 16:45:32.300605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6a5710ac133'
down_revision: Union[str, Sequence[str], None] = '2ce1ec00252b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fall_log', sa.Column('responsed', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('fall_log', sa.Column('notified', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('fall_log', sa.Column('notified_to_caregiver', sa.Boolean(), server_default='False', nullable=False))
    op.drop_column('sleep_retrain_log', 'bvp')
    op.drop_column('sleep_retrain_log', 'sao2')
    op.drop_column('stress_retrain_log', 'wrist_temperature_c_mean')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stress_retrain_log', sa.Column('wrist_temperature_c_mean', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.add_column('sleep_retrain_log', sa.Column('sao2', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.add_column('sleep_retrain_log', sa.Column('bvp', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.drop_column('fall_log', 'notified_to_caregiver')
    op.drop_column('fall_log', 'notified')
    op.drop_column('fall_log', 'responsed')
    # ### end Alembic commands ###
